#!/bin/bash

cput=$(vmstat 2 2| tail -1 | awk '{print(100 - $15)}')
#if [[ $BLOCK_BUTTON == [0-3] ]]; then
#	for i in {0..7}; do
#		cpu=+$(cat /proc/stat | grep "cpu$i" | awk '{ print (100 - ($5 * 100)/($2 + $3 + $4 + $5 + $6 + $7 +$8)) }')
#	done
#fi
#
#for i in {0..16}; do
#	cpu+="$(cat /proc/stat | grep "cpu$i " | awk '{ print (100 - ($5 * 100)/($2 + $3 + $4 + $5 + $6 + $7 +$8)) }'; echo -en "\n")"
#done
#
#echo $cpu | sed 's/ /\n/g' | read -a cpu 
#
#echo "cpu$cpu[*]"
#
#case $BLOCK_BUTTON in
#	1) notify-send "CPU USAGE" "$(ps -eo comm,pcpu --sort -pcpu | head)" ;;
#	3) notify-send "CPU CORES" "$(printf "Total:\t%0.1f%%\ncpu0:\t%0.1f%%\ncpu1:\t%0.1f%%\ncpu2:\t%0.1f%%\ncpu3:\t%0.1f%%" $cput $cpu0 $cpu1 $cpu2 $cpu3)" ;;
#esac

echo "$cput%"
echo "$cput%"

case $cput in
	100|[8-9][0-9]) echo "#FF0000" ;;
	[6-7][0-9]    ) echo "#FF8800" ;;
	[4-5][0-9]    ) echo "#FFFF00" ;;
	*             ) echo "#00FF00" ;;
esac
